// This is code generated by style_generator.rb script. Do not modify this file directly since every changes will be overwritten by script.
// Date: 2016-09-13 23:43:50 +0300
public extension UIView {
    /** Updates `transform` property of `UIView` instance. */
    public static func transform(transform: CGAffineTransform) -> Style {
        return Style("Transform \(transform)") {
            (view: UIView) in
            view.transform = transform
        }
    }

    /** Updates `backgroundColor` property of `UIView` instance. */
    public static func backgroundColor(backgroundColor: ColorType) -> Style {
        return Style("Background Color \(backgroundColor)") {
            (view: UIView) in
            view.backgroundColor = backgroundColor
        }
    }

    /** Updates `tintColor` property of `UIView` instance. */
    public static func tintColor(tintColor: ColorType) -> Style {
        return Style("Tint Color \(tintColor)") {
            (view: UIView) in
            view.tintColor = tintColor
        }
    }
}
