// This is code generated by style_generator.rb script. Do not modify this file directly since every changes will be overwritten by script.
// Date: 2016-09-22 16:08:53 +0300
import UIKit
import FreestylerCore



public extension UIButton {
    /** Updates `adjustsImageWhenHighlighted` property of `UIButton` instance. */
    public static func adjustsImageWhenHighlighted(adjustsImageWhenHighlighted: Bool) -> Style {
        return Style("Adjusts Image When Highlighted \(adjustsImageWhenHighlighted)") {
            (button: UIButton) in
            button.adjustsImageWhenHighlighted = adjustsImageWhenHighlighted
        }
    }

    /** Updates `adjustsImageWhenDisabled` property of `UIButton` instance. */
    public static func adjustsImageWhenDisabled(adjustsImageWhenDisabled: Bool) -> Style {
        return Style("Adjusts Image When Disabled \(adjustsImageWhenDisabled)") {
            (button: UIButton) in
            button.adjustsImageWhenDisabled = adjustsImageWhenDisabled
        }
    }

    /** Updates `showsTouchWhenHighlighted` property of `UIButton` instance. */
    public static func showsTouchWhenHighlighted(showsTouchWhenHighlighted: Bool) -> Style {
        return Style("Shows Touch When Highlighted \(showsTouchWhenHighlighted)") {
            (button: UIButton) in
            button.showsTouchWhenHighlighted = showsTouchWhenHighlighted
        }
    }

    /** Updates `contentEdgeInsets` property of `UIButton` instance. */
    public static func contentEdgeInsets(contentEdgeInsets: UIEdgeInsets) -> Style {
        return Style("Content Edge Insets \(contentEdgeInsets)") {
            (button: UIButton) in
            button.contentEdgeInsets = contentEdgeInsets
        }
    }

    /** Updates `titleEdgeInsets` property of `UIButton` instance. */
    public static func titleEdgeInsets(titleEdgeInsets: UIEdgeInsets) -> Style {
        return Style("Title Edge Insets \(titleEdgeInsets)") {
            (button: UIButton) in
            button.titleEdgeInsets = titleEdgeInsets
        }
    }

    /** Updates `imageEdgeInsets` property of `UIButton` instance. */
    public static func imageEdgeInsets(imageEdgeInsets: UIEdgeInsets) -> Style {
        return Style("Image Edge Insets \(imageEdgeInsets)") {
            (button: UIButton) in
            button.imageEdgeInsets = imageEdgeInsets
        }
    }
}
