// This is code generated by style_generator.rb script. Do not modify this file directly since every changes will be overwritten by script.
// Date: 2016-09-22 16:08:53 +0300
import UIKit
import FreestylerCore



public extension UILabel {
    /** Updates `textColor` property of `UILabel` instance. */
    public static func textColor(textColor: ColorType?) -> Style {
        return Style("Text Color \(textColor)") {
            (label: UILabel) in
            label.textColor = textColor?.color
        }
    }

    /** Updates `font` property of `UILabel` instance. */
    public static func font(font: FontType?) -> Style {
        return Style("Font \(font)") {
            (label: UILabel) in
            label.font = font?.font
        }
    }

    /** Updates `textAlignment` property of `UILabel` instance. */
    public static func textAlignment(textAlignment: NSTextAlignment) -> Style {
        return Style("Text Alignment \(textAlignment)") {
            (label: UILabel) in
            label.textAlignment = textAlignment
        }
    }

    /** Updates `lineBreakMode` property of `UILabel` instance. */
    public static func lineBreakMode(lineBreakMode: NSLineBreakMode) -> Style {
        return Style("Line Break Mode \(lineBreakMode)") {
            (label: UILabel) in
            label.lineBreakMode = lineBreakMode
        }
    }

    /** Updates `adjustsFontSizeToFitWidth` property of `UILabel` instance. */
    public static func adjustsFontSizeToFitWidth(adjustsFontSizeToFitWidth: Bool) -> Style {
        return Style("Adjusts Font Size To Fit Width \(adjustsFontSizeToFitWidth)") {
            (label: UILabel) in
            label.adjustsFontSizeToFitWidth = adjustsFontSizeToFitWidth
        }
    }

    /** Updates `allowsDefaultTighteningForTruncation` property of `UILabel` instance. */
    public static func allowsDefaultTighteningForTruncation(allowsDefaultTighteningForTruncation: Bool) -> Style {
        return Style("Allows Default Tightening For Truncation \(allowsDefaultTighteningForTruncation)") {
            (label: UILabel) in
            label.allowsDefaultTighteningForTruncation = allowsDefaultTighteningForTruncation
        }
    }

    /** Updates `baselineAdjustment` property of `UILabel` instance. */
    public static func baselineAdjustment(baselineAdjustment: UIBaselineAdjustment) -> Style {
        return Style("Baseline Adjustment \(baselineAdjustment)") {
            (label: UILabel) in
            label.baselineAdjustment = baselineAdjustment
        }
    }

    /** Updates `minimumScaleFactor` property of `UILabel` instance. */
    public static func minimumScaleFactor(minimumScaleFactor: CGFloat) -> Style {
        return Style("Minimum Scale Factor \(minimumScaleFactor)") {
            (label: UILabel) in
            label.minimumScaleFactor = minimumScaleFactor
        }
    }

    /** Updates `numberOfLines` property of `UILabel` instance. */
    public static func numberOfLines(numberOfLines: Int) -> Style {
        return Style("Number Of Lines \(numberOfLines)") {
            (label: UILabel) in
            label.numberOfLines = numberOfLines
        }
    }

    /** Updates `highlightedTextColor` property of `UILabel` instance. */
    public static func highlightedTextColor(highlightedTextColor: ColorType?) -> Style {
        return Style("Highlighted Text Color \(highlightedTextColor)") {
            (label: UILabel) in
            label.highlightedTextColor = highlightedTextColor?.color
        }
    }

    /** Updates `shadowColor` property of `UILabel` instance. */
    public static func shadowColor(shadowColor: ColorType) -> Style {
        return Style("Shadow Color \(shadowColor)") {
            (label: UILabel) in
            label.shadowColor = shadowColor.color
        }
    }

    /** Updates `shadowOffset` property of `UILabel` instance. */
    public static func shadowOffset(shadowOffset: CGSize) -> Style {
        return Style("Shadow Offset \(shadowOffset)") {
            (label: UILabel) in
            label.shadowOffset = shadowOffset
        }
    }

    /** Updates `preferredMaxLayoutWidth` property of `UILabel` instance. */
    public static func preferredMaxLayoutWidth(preferredMaxLayoutWidth: CGFloat) -> Style {
        return Style("Preferred Max Layout Width \(preferredMaxLayoutWidth)") {
            (label: UILabel) in
            label.preferredMaxLayoutWidth = preferredMaxLayoutWidth
        }
    }
}
