// This is code generated by style_generator.rb script. Do not modify this file directly since every changes will be overwritten by script.
// Date: 2016-09-22 16:08:53 +0300
import UIKit
import FreestylerCore



public extension UINavigationBar {
    /** Updates `backIndicatorImage` property of `UINavigationBar` instance. */
    public static func backIndicatorImage(backIndicatorImage: UIImage?) -> Style {
        return Style("Back Indicator Image \(backIndicatorImage)") {
            (navigationBar: UINavigationBar) in
            navigationBar.backIndicatorImage = backIndicatorImage
        }
    }

    /** Updates `backIndicatorTransitionMaskImage` property of `UINavigationBar` instance. */
    public static func backIndicatorTransitionMaskImage(backIndicatorTransitionMaskImage: UIImage?) -> Style {
        return Style("Back Indicator Transition Mask Image \(backIndicatorTransitionMaskImage)") {
            (navigationBar: UINavigationBar) in
            navigationBar.backIndicatorTransitionMaskImage = backIndicatorTransitionMaskImage
        }
    }

    /** Updates `barStyle` property of `UINavigationBar` instance. */
    public static func barStyle(barStyle: UIBarStyle) -> Style {
        return Style("Bar Style \(barStyle)") {
            (navigationBar: UINavigationBar) in
            navigationBar.barStyle = barStyle
        }
    }

    /** Updates `barTintColor` property of `UINavigationBar` instance. */
    public static func barTintColor(barTintColor: ColorType?) -> Style {
        return Style("Bar Tint Color \(barTintColor)") {
            (navigationBar: UINavigationBar) in
            navigationBar.barTintColor = barTintColor?.color
        }
    }

    /** Updates `shadowImage` property of `UINavigationBar` instance. */
    public static func shadowImage(shadowImage: UIImage?) -> Style {
        return Style("Shadow Image \(shadowImage)") {
            (navigationBar: UINavigationBar) in
            navigationBar.shadowImage = shadowImage
        }
    }

    /** Updates `translucent` property of `UINavigationBar` instance. */
    public static func translucent(translucent: Bool) -> Style {
        return Style("Translucent \(translucent)") {
            (navigationBar: UINavigationBar) in
            navigationBar.translucent = translucent
        }
    }

    /** Updates `titleTextAttributes` property of `UINavigationBar` instance. */
    public static func titleTextAttributes(titleTextAttributes: [String: AnyObject]?) -> Style {
        return Style("Title Text Attributes \(titleTextAttributes)") {
            (navigationBar: UINavigationBar) in
            navigationBar.titleTextAttributes = titleTextAttributes
        }
    }
}
