// This is code generated by style_generator.rb script. Do not modify this file directly since every changes will be overwritten by script.
// Date: 2016-09-24 00:35:39 +0300
import UIKit
import FreestylerCore



public extension UINavigationBar {
    /** Updates `backIndicatorImage` property of `UINavigationBar` instance. */
    public static func backIndicatorImage(backIndicatorImage: UIImage?) -> Style {
        return Style("Back Indicator Image \(backIndicatorImage)") {
            (styleable: UINavigationBar) in
            styleable.backIndicatorImage = backIndicatorImage
        }
    }

    /** Updates `backIndicatorTransitionMaskImage` property of `UINavigationBar` instance. */
    public static func backIndicatorTransitionMaskImage(backIndicatorTransitionMaskImage: UIImage?) -> Style {
        return Style("Back Indicator Transition Mask Image \(backIndicatorTransitionMaskImage)") {
            (styleable: UINavigationBar) in
            styleable.backIndicatorTransitionMaskImage = backIndicatorTransitionMaskImage
        }
    }

    /** Updates `barStyle` property of `UINavigationBar` instance. */
    public static func barStyle(barStyle: UIBarStyle) -> Style {
        return Style("Bar Style \(barStyle)") {
            (styleable: UINavigationBar) in
            styleable.barStyle = barStyle
        }
    }

    /** Updates `barTintColor` property of `UINavigationBar` instance. */
    public static func barTintColor(barTintColor: ColorType?) -> Style {
        return Style("Bar Tint Color \(barTintColor)") {
            (styleable: UINavigationBar) in
            styleable.barTintColor = barTintColor?.color
        }
    }

    /** Updates `shadowImage` property of `UINavigationBar` instance. */
    public static func shadowImage(shadowImage: UIImage?) -> Style {
        return Style("Shadow Image \(shadowImage)") {
            (styleable: UINavigationBar) in
            styleable.shadowImage = shadowImage
        }
    }

    /** Updates `translucent` property of `UINavigationBar` instance. */
    public static func translucent(translucent: Bool) -> Style {
        return Style("Translucent \(translucent)") {
            (styleable: UINavigationBar) in
            styleable.translucent = translucent
        }
    }

    /** Updates `titleTextAttributes` property of `UINavigationBar` instance. */
    public static func titleTextAttributes(titleTextAttributes: [String: AnyObject]?) -> Style {
        return Style("Title Text Attributes \(titleTextAttributes)") {
            (styleable: UINavigationBar) in
            styleable.titleTextAttributes = titleTextAttributes
        }
    }
}
