// This is code generated by style_generator.rb script. Do not modify this file directly since every changes will be overwritten by script.
// Date: 2016-09-18 00:28:47 +0300
import UIKit
import FreestylerCore



public extension UIProgressView {
    /** Updates `progressViewStyle` property of `UIProgressView` instance. */
    public static func progressViewStyle(progressViewStyle: UIProgressViewStyle) -> Style {
        return Style("Progress View Style \(progressViewStyle)") {
            (progressView: UIProgressView) in
            progressView.progressViewStyle = progressViewStyle
        }
    }

    /** Updates `progressTintColor` property of `UIProgressView` instance. */
    public static func progressTintColor(progressTintColor: ColorType) -> Style {
        return Style("Progress Tint Color \(progressTintColor)") {
            (progressView: UIProgressView) in
            progressView.progressTintColor = progressTintColor.color
        }
    }

    /** Updates `progressImage` property of `UIProgressView` instance. */
    public static func progressImage(progressImage: UIImage?) -> Style {
        return Style("Progress Image \(progressImage)") {
            (progressView: UIProgressView) in
            progressView.progressImage = progressImage
        }
    }

    /** Updates `trackTintColor` property of `UIProgressView` instance. */
    public static func trackTintColor(trackTintColor: ColorType) -> Style {
        return Style("Track Tint Color \(trackTintColor)") {
            (progressView: UIProgressView) in
            progressView.trackTintColor = trackTintColor.color
        }
    }

    /** Updates `trackImage` property of `UIProgressView` instance. */
    public static func trackImage(trackImage: UIImage?) -> Style {
        return Style("Track Image \(trackImage)") {
            (progressView: UIProgressView) in
            progressView.trackImage = trackImage
        }
    }
}
