// This is code generated by style_generator.rb script. Do not modify this file directly since every changes will be overwritten by script.
// Date: 2016-09-24 01:03:32 +0300
import UIKit
import FreestylerCore



public extension UIScrollView {
    /** Updates `indicatorStyle` property of `UIScrollView` instance. */
    public static func styleIndicatorStyle(indicatorStyle: UIScrollViewIndicatorStyle) -> Style {
        return Style("Indicator Style \(indicatorStyle)") {
            (styleable: UIScrollView) in
            styleable.indicatorStyle = indicatorStyle
        }
    }

    /** Updates `scrollIndicatorInsets` property of `UIScrollView` instance. */
    public static func styleScrollIndicatorInsets(scrollIndicatorInsets: UIEdgeInsets) -> Style {
        return Style("Scroll Indicator Insets \(scrollIndicatorInsets)") {
            (styleable: UIScrollView) in
            styleable.scrollIndicatorInsets = scrollIndicatorInsets
        }
    }

    /** Updates `showsHorizontalScrollIndicator` property of `UIScrollView` instance. */
    public static func styleShowsHorizontalScrollIndicator(showsHorizontalScrollIndicator: Bool) -> Style {
        return Style("Shows Horizontal Scroll Indicator \(showsHorizontalScrollIndicator)") {
            (styleable: UIScrollView) in
            styleable.showsHorizontalScrollIndicator = showsHorizontalScrollIndicator
        }
    }

    /** Updates `showsVerticalScrollIndicator` property of `UIScrollView` instance. */
    public static func styleShowsVerticalScrollIndicator(showsVerticalScrollIndicator: Bool) -> Style {
        return Style("Shows Vertical Scroll Indicator \(showsVerticalScrollIndicator)") {
            (styleable: UIScrollView) in
            styleable.showsVerticalScrollIndicator = showsVerticalScrollIndicator
        }
    }

    /** Updates `bounces` property of `UIScrollView` instance. */
    public static func styleBounces(bounces: Bool) -> Style {
        return Style("Bounces \(bounces)") {
            (styleable: UIScrollView) in
            styleable.bounces = bounces
        }
    }

    /** Updates `alwaysBounceVertical` property of `UIScrollView` instance. */
    public static func styleAlwaysBounceVertical(alwaysBounceVertical: Bool) -> Style {
        return Style("Always Bounce Vertical \(alwaysBounceVertical)") {
            (styleable: UIScrollView) in
            styleable.alwaysBounceVertical = alwaysBounceVertical
        }
    }

    /** Updates `alwaysBounceHorizontal` property of `UIScrollView` instance. */
    public static func styleAlwaysBounceHorizontal(alwaysBounceHorizontal: Bool) -> Style {
        return Style("Always Bounce Horizontal \(alwaysBounceHorizontal)") {
            (styleable: UIScrollView) in
            styleable.alwaysBounceHorizontal = alwaysBounceHorizontal
        }
    }

    /** Updates `decelerationRate` property of `UIScrollView` instance. */
    public static func styleDecelerationRate(decelerationRate: CGFloat) -> Style {
        return Style("Deceleration Rate \(decelerationRate)") {
            (styleable: UIScrollView) in
            styleable.decelerationRate = decelerationRate
        }
    }

    /** Updates `contentInset` property of `UIScrollView` instance. */
    public static func styleContentInset(contentInset: UIEdgeInsets) -> Style {
        return Style("Content Inset \(contentInset)") {
            (styleable: UIScrollView) in
            styleable.contentInset = contentInset
        }
    }

    /** Updates `keyboardDismissMode` property of `UIScrollView` instance. */
    public static func styleKeyboardDismissMode(keyboardDismissMode: UIScrollViewKeyboardDismissMode) -> Style {
        return Style("Keyboard Dismiss Mode \(keyboardDismissMode)") {
            (styleable: UIScrollView) in
            styleable.keyboardDismissMode = keyboardDismissMode
        }
    }
}
