// This is code generated by style_generator.rb script. Do not modify this file directly since every changes will be overwritten by script.
// Date: 2016-09-22 16:08:53 +0300
import UIKit
import FreestylerCore



public extension UIScrollView {
    /** Updates `indicatorStyle` property of `UIScrollView` instance. */
    public static func indicatorStyle(indicatorStyle: UIScrollViewIndicatorStyle) -> Style {
        return Style("Indicator Style \(indicatorStyle)") {
            (scrollView: UIScrollView) in
            scrollView.indicatorStyle = indicatorStyle
        }
    }

    /** Updates `scrollIndicatorInsets` property of `UIScrollView` instance. */
    public static func scrollIndicatorInsets(scrollIndicatorInsets: UIEdgeInsets) -> Style {
        return Style("Scroll Indicator Insets \(scrollIndicatorInsets)") {
            (scrollView: UIScrollView) in
            scrollView.scrollIndicatorInsets = scrollIndicatorInsets
        }
    }

    /** Updates `showsHorizontalScrollIndicator` property of `UIScrollView` instance. */
    public static func showsHorizontalScrollIndicator(showsHorizontalScrollIndicator: Bool) -> Style {
        return Style("Shows Horizontal Scroll Indicator \(showsHorizontalScrollIndicator)") {
            (scrollView: UIScrollView) in
            scrollView.showsHorizontalScrollIndicator = showsHorizontalScrollIndicator
        }
    }

    /** Updates `showsVerticalScrollIndicator` property of `UIScrollView` instance. */
    public static func showsVerticalScrollIndicator(showsVerticalScrollIndicator: Bool) -> Style {
        return Style("Shows Vertical Scroll Indicator \(showsVerticalScrollIndicator)") {
            (scrollView: UIScrollView) in
            scrollView.showsVerticalScrollIndicator = showsVerticalScrollIndicator
        }
    }

    /** Updates `bounces` property of `UIScrollView` instance. */
    public static func bounces(bounces: Bool) -> Style {
        return Style("Bounces \(bounces)") {
            (scrollView: UIScrollView) in
            scrollView.bounces = bounces
        }
    }

    /** Updates `alwaysBounceVertical` property of `UIScrollView` instance. */
    public static func alwaysBounceVertical(alwaysBounceVertical: Bool) -> Style {
        return Style("Always Bounce Vertical \(alwaysBounceVertical)") {
            (scrollView: UIScrollView) in
            scrollView.alwaysBounceVertical = alwaysBounceVertical
        }
    }

    /** Updates `alwaysBounceHorizontal` property of `UIScrollView` instance. */
    public static func alwaysBounceHorizontal(alwaysBounceHorizontal: Bool) -> Style {
        return Style("Always Bounce Horizontal \(alwaysBounceHorizontal)") {
            (scrollView: UIScrollView) in
            scrollView.alwaysBounceHorizontal = alwaysBounceHorizontal
        }
    }

    /** Updates `decelerationRate` property of `UIScrollView` instance. */
    public static func decelerationRate(decelerationRate: CGFloat) -> Style {
        return Style("Deceleration Rate \(decelerationRate)") {
            (scrollView: UIScrollView) in
            scrollView.decelerationRate = decelerationRate
        }
    }

    /** Updates `contentInset` property of `UIScrollView` instance. */
    public static func contentInset(contentInset: UIEdgeInsets) -> Style {
        return Style("Content Inset \(contentInset)") {
            (scrollView: UIScrollView) in
            scrollView.contentInset = contentInset
        }
    }

    /** Updates `keyboardDismissMode` property of `UIScrollView` instance. */
    public static func keyboardDismissMode(keyboardDismissMode: UIScrollViewKeyboardDismissMode) -> Style {
        return Style("Keyboard Dismiss Mode \(keyboardDismissMode)") {
            (scrollView: UIScrollView) in
            scrollView.keyboardDismissMode = keyboardDismissMode
        }
    }
}
