// This is code generated by style_generator.rb script. Do not modify this file directly since every changes will be overwritten by script.
// Date: 2016-09-24 00:35:39 +0300
import UIKit
import FreestylerCore



public extension UITabBar {
    /** Updates `barStyle` property of `UITabBar` instance. */
    public static func barStyle(barStyle: UIBarStyle) -> Style {
        return Style("Bar Style \(barStyle)") {
            (styleable: UITabBar) in
            styleable.barStyle = barStyle
        }
    }

    /** Updates `translucent` property of `UITabBar` instance. */
    public static func translucent(translucent: Bool) -> Style {
        return Style("Translucent \(translucent)") {
            (styleable: UITabBar) in
            styleable.translucent = translucent
        }
    }

    /** Updates `barTintColor` property of `UITabBar` instance. */
    public static func barTintColor(barTintColor: ColorType?) -> Style {
        return Style("Bar Tint Color \(barTintColor)") {
            (styleable: UITabBar) in
            styleable.barTintColor = barTintColor?.color
        }
    }

    /** Updates `itemPositioning` property of `UITabBar` instance. */
    public static func itemPositioning(itemPositioning: UITabBarItemPositioning) -> Style {
        return Style("Item Positioning \(itemPositioning)") {
            (styleable: UITabBar) in
            styleable.itemPositioning = itemPositioning
        }
    }

    /** Updates `itemSpacing` property of `UITabBar` instance. */
    public static func itemSpacing(itemSpacing: CGFloat) -> Style {
        return Style("Item Spacing \(itemSpacing)") {
            (styleable: UITabBar) in
            styleable.itemSpacing = itemSpacing
        }
    }

    /** Updates `itemWidth` property of `UITabBar` instance. */
    public static func itemWidth(itemWidth: CGFloat) -> Style {
        return Style("Item Width \(itemWidth)") {
            (styleable: UITabBar) in
            styleable.itemWidth = itemWidth
        }
    }

    /** Updates `backgroundImage` property of `UITabBar` instance. */
    public static func backgroundImage(backgroundImage: UIImage?) -> Style {
        return Style("Background Image \(backgroundImage)") {
            (styleable: UITabBar) in
            styleable.backgroundImage = backgroundImage
        }
    }

    /** Updates `shadowImage` property of `UITabBar` instance. */
    public static func shadowImage(shadowImage: UIImage?) -> Style {
        return Style("Shadow Image \(shadowImage)") {
            (styleable: UITabBar) in
            styleable.shadowImage = shadowImage
        }
    }

    /** Updates `selectionIndicatorImage` property of `UITabBar` instance. */
    public static func selectionIndicatorImage(selectionIndicatorImage: UIImage?) -> Style {
        return Style("Selection Indicator Image \(selectionIndicatorImage)") {
            (styleable: UITabBar) in
            styleable.selectionIndicatorImage = selectionIndicatorImage
        }
    }
}
