// This is code generated by style_generator.rb script. Do not modify this file directly since every changes will be overwritten by script.
// Date: 2016-09-22 16:08:53 +0300
import UIKit
import FreestylerCore



public extension UITableView {
    /** Updates `rowHeight` property of `UITableView` instance. */
    public static func rowHeight(rowHeight: CGFloat) -> Style {
        return Style("Row Height \(rowHeight)") {
            (tableView: UITableView) in
            tableView.rowHeight = rowHeight
        }
    }

    /** Updates `separatorStyle` property of `UITableView` instance. */
    public static func separatorStyle(separatorStyle: UITableViewCellSeparatorStyle) -> Style {
        return Style("Separator Style \(separatorStyle)") {
            (tableView: UITableView) in
            tableView.separatorStyle = separatorStyle
        }
    }

    /** Updates `separatorColor` property of `UITableView` instance. */
    public static func separatorColor(separatorColor: ColorType?) -> Style {
        return Style("Separator Color \(separatorColor)") {
            (tableView: UITableView) in
            tableView.separatorColor = separatorColor?.color
        }
    }

    /** Updates `separatorEffect` property of `UITableView` instance. */
    public static func separatorEffect(separatorEffect: UIVisualEffect?) -> Style {
        return Style("Separator Effect \(separatorEffect)") {
            (tableView: UITableView) in
            tableView.separatorEffect = separatorEffect
        }
    }

    /** Updates `backgroundView` property of `UITableView` instance. */
    public static func backgroundView(backgroundView: UIView?) -> Style {
        return Style("Background View \(backgroundView)") {
            (tableView: UITableView) in
            tableView.backgroundView = backgroundView
        }
    }

    /** Updates `separatorInset` property of `UITableView` instance. */
    public static func separatorInset(separatorInset: UIEdgeInsets) -> Style {
        return Style("Separator Inset \(separatorInset)") {
            (tableView: UITableView) in
            tableView.separatorInset = separatorInset
        }
    }

    /** Updates `cellLayoutMarginsFollowReadableWidth` property of `UITableView` instance. */
    public static func cellLayoutMarginsFollowReadableWidth(cellLayoutMarginsFollowReadableWidth: Bool) -> Style {
        return Style("Cell Layout Margins Follow Readable Width \(cellLayoutMarginsFollowReadableWidth)") {
            (tableView: UITableView) in
            tableView.cellLayoutMarginsFollowReadableWidth = cellLayoutMarginsFollowReadableWidth
        }
    }
}
