// This is code generated by style_generator.rb script. Do not modify this file directly since every changes will be overwritten by script.
// Date: 2016-09-22 11:24:54 +0300
import UIKit
import FreestylerCore



public extension UIToolbar {
}
