// This is code generated by style_generator.rb script. Do not modify this file directly since every changes will be overwritten by script.
// Date: 2016-09-29 01:58:34 +0300
import UIKit
import FreestylerCore



public extension UIActivityIndicatorView {
    /** Updates `activityIndicatorViewStyle` property of `UIActivityIndicatorView` instance. */
    public static func styleActivityIndicatorViewStyle(activityIndicatorViewStyle: UIActivityIndicatorViewStyle) -> Style {
        return Style("Activity Indicator View Style \(activityIndicatorViewStyle)") {
            (styleable: UIActivityIndicatorView) in
            styleable.activityIndicatorViewStyle = activityIndicatorViewStyle
        }
    }

    /** Updates `color` property of `UIActivityIndicatorView` instance. */
    public static func styleColor(color: ColorType) -> Style {
        return Style("Color \(color)") {
            (styleable: UIActivityIndicatorView) in
            styleable.color = color.color
        }
    }
}
