// This is code generated by style_generator.rb script. Do not modify this file directly since every changes will be overwritten by script.
// Date: 2016-09-29 01:24:34 +0300
import UIKit
import FreestylerCore



public extension UIButton {
    /** Updates `adjustsImageWhenHighlighted` property of `UIButton` instance. */
    public static func styleAdjustsImageWhenHighlighted(adjustsImageWhenHighlighted: Bool) -> Style {
        return Style("Adjusts Image When Highlighted \(adjustsImageWhenHighlighted)") {
            (styleable: UIButton) in
            styleable.adjustsImageWhenHighlighted = adjustsImageWhenHighlighted
        }
    }

    /** Updates `adjustsImageWhenDisabled` property of `UIButton` instance. */
    public static func styleAdjustsImageWhenDisabled(adjustsImageWhenDisabled: Bool) -> Style {
        return Style("Adjusts Image When Disabled \(adjustsImageWhenDisabled)") {
            (styleable: UIButton) in
            styleable.adjustsImageWhenDisabled = adjustsImageWhenDisabled
        }
    }

    /** Updates `showsTouchWhenHighlighted` property of `UIButton` instance. */
    public static func styleShowsTouchWhenHighlighted(showsTouchWhenHighlighted: Bool) -> Style {
        return Style("Shows Touch When Highlighted \(showsTouchWhenHighlighted)") {
            (styleable: UIButton) in
            styleable.showsTouchWhenHighlighted = showsTouchWhenHighlighted
        }
    }

    /** Updates `contentEdgeInsets` property of `UIButton` instance. */
    public static func styleContentEdgeInsets(contentEdgeInsets: UIEdgeInsets) -> Style {
        return Style("Content Edge Insets \(contentEdgeInsets)") {
            (styleable: UIButton) in
            styleable.contentEdgeInsets = contentEdgeInsets
        }
    }

    /** Updates `titleEdgeInsets` property of `UIButton` instance. */
    public static func styleTitleEdgeInsets(titleEdgeInsets: UIEdgeInsets) -> Style {
        return Style("Title Edge Insets \(titleEdgeInsets)") {
            (styleable: UIButton) in
            styleable.titleEdgeInsets = titleEdgeInsets
        }
    }

    /** Updates `imageEdgeInsets` property of `UIButton` instance. */
    public static func styleImageEdgeInsets(imageEdgeInsets: UIEdgeInsets) -> Style {
        return Style("Image Edge Insets \(imageEdgeInsets)") {
            (styleable: UIButton) in
            styleable.imageEdgeInsets = imageEdgeInsets
        }
    }

    /** Updates `reversesTitleShadowWhenHighlighted` property of `UIButton` instance. */
    public static func styleReversesTitleShadowWhenHighlighted(reversesTitleShadowWhenHighlighted: Bool) -> Style {
        return Style("Reverses Title Shadow When Highlighted \(reversesTitleShadowWhenHighlighted)") {
            (styleable: UIButton) in
            styleable.reversesTitleShadowWhenHighlighted = reversesTitleShadowWhenHighlighted
        }
    }
}
