// This is code generated by style_generator.rb script. Do not modify this file directly since every changes will be overwritten by script.
// Date: 2016-09-29 01:24:34 +0300
import UIKit
import FreestylerCore



public extension UICollectionViewCell {
    /** Updates `backgroundView` property of `UICollectionViewCell` instance. */
    public static func styleBackgroundView(backgroundView: UIView?) -> Style {
        return Style("Background View \(backgroundView)") {
            (styleable: UICollectionViewCell) in
            styleable.backgroundView = backgroundView
        }
    }

    /** Updates `selectedBackgroundView` property of `UICollectionViewCell` instance. */
    public static func styleSelectedBackgroundView(selectedBackgroundView: UIView?) -> Style {
        return Style("Selected Background View \(selectedBackgroundView)") {
            (styleable: UICollectionViewCell) in
            styleable.selectedBackgroundView = selectedBackgroundView
        }
    }
}
