// This is code generated by style_generator.rb script. Do not modify this file directly since every changes will be overwritten by script.
// Date: 2016-09-29 01:58:34 +0300
import UIKit
import FreestylerCore



public extension UIPageControl {
    /** Updates `pageIndicatorTintColor` property of `UIPageControl` instance. */
    public static func stylePageIndicatorTintColor(pageIndicatorTintColor: ColorType?) -> Style {
        return Style("Page Indicator Tint Color \(pageIndicatorTintColor)") {
            (styleable: UIPageControl) in
            styleable.pageIndicatorTintColor = pageIndicatorTintColor?.color
        }
    }

    /** Updates `currentPageIndicatorTintColor` property of `UIPageControl` instance. */
    public static func styleCurrentPageIndicatorTintColor(currentPageIndicatorTintColor: ColorType?) -> Style {
        return Style("Current Page Indicator Tint Color \(currentPageIndicatorTintColor)") {
            (styleable: UIPageControl) in
            styleable.currentPageIndicatorTintColor = currentPageIndicatorTintColor?.color
        }
    }

    /** Updates `defersCurrentPageDisplay` property of `UIPageControl` instance. */
    public static func styleDefersCurrentPageDisplay(defersCurrentPageDisplay: Bool) -> Style {
        return Style("Defers Current Page Display \(defersCurrentPageDisplay)") {
            (styleable: UIPageControl) in
            styleable.defersCurrentPageDisplay = defersCurrentPageDisplay
        }
    }
}
