// This is code generated by style_generator.rb script. Do not modify this file directly since every changes will be overwritten by script.
// Date: 2016-09-29 01:24:34 +0300
import UIKit
import FreestylerCore



public extension UITextView {
    /** Updates `font` property of `UITextView` instance. */
    public static func styleFont(font: FontType?) -> Style {
        return Style("Font \(font)") {
            (styleable: UITextView) in
            styleable.font = font?.font
        }
    }

    /** Updates `textColor` property of `UITextView` instance. */
    public static func styleTextColor(textColor: ColorType?) -> Style {
        return Style("Text Color \(textColor)") {
            (styleable: UITextView) in
            styleable.textColor = textColor?.color
        }
    }

    /** Updates `editable` property of `UITextView` instance. */
    public static func styleEditable(editable: Bool) -> Style {
        return Style("Editable \(editable)") {
            (styleable: UITextView) in
            styleable.editable = editable
        }
    }

    /** Updates `allowsEditingTextAttributes` property of `UITextView` instance. */
    public static func styleAllowsEditingTextAttributes(allowsEditingTextAttributes: Bool) -> Style {
        return Style("Allows Editing Text Attributes \(allowsEditingTextAttributes)") {
            (styleable: UITextView) in
            styleable.allowsEditingTextAttributes = allowsEditingTextAttributes
        }
    }

    /** Updates `textAlignment` property of `UITextView` instance. */
    public static func styleTextAlignment(textAlignment: NSTextAlignment) -> Style {
        return Style("Text Alignment \(textAlignment)") {
            (styleable: UITextView) in
            styleable.textAlignment = textAlignment
        }
    }

    /** Updates `typingAttributes` property of `UITextView` instance. */
    public static func styleTypingAttributes(typingAttributes: [String : AnyObject]) -> Style {
        return Style("Typing Attributes \(typingAttributes)") {
            (styleable: UITextView) in
            styleable.typingAttributes = typingAttributes
        }
    }

    /** Updates `linkTextAttributes` property of `UITextView` instance. */
    public static func styleLinkTextAttributes(linkTextAttributes: [String : AnyObject]?) -> Style {
        return Style("Link Text Attributes \(linkTextAttributes)") {
            (styleable: UITextView) in
            styleable.linkTextAttributes = linkTextAttributes
        }
    }

    /** Updates `textContainerInset` property of `UITextView` instance. */
    public static func styleTextContainerInset(textContainerInset: UIEdgeInsets) -> Style {
        return Style("Text Container Inset \(textContainerInset)") {
            (styleable: UITextView) in
            styleable.textContainerInset = textContainerInset
        }
    }
}
